# Generated by Django 3.1.6 on 2021-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP address')),
                ('dataTime', models.CharField(max_length=26, verbose_name='Время')),
                ('postId', models.ForeignKey("Post", on_delete=models.CASCADE)),
            ],
        ),
    ]
